protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
                $Criteria = new CDbCriteria();//represent for query such as conditions, ordering by, limit/offset. 
                $Criteria -> select = "*";
                $Criteria -> order = "TenHangSX ASC";
		// renders the view file 'protected/views/site/index.php'
		// using the default layout 'protected/views/layouts/main.php'
		
                
                
                $newCriteria = new CDbCriteria();
                $newCriteria -> select =  "*";
                $newCriteria->limit = "8";
                
                $this->render('index', array ('newPrd' => Sanpham::model()->findAll($newCriteria), 'Companies' => Company::model()->findAll($Criteria)));
	}

	/**
	 * This is the action to handle external exceptions.
	 */
        
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}
        
        public function actionDetails()
	{
                
                
                $comCriteria1 = new CDbCriteria();
                $comCriteria1->select = "`MaHangSX`, `TenHangSX`";
                
                
        
             if ($_GET["pid"])
                {
                    $spCriteria = new CDbCriteria();
                    $spCriteria->select = "*";
                    $spCriteria->condition = "MaSP = ".$_GET["pid"];
                    
                    
                    $this->render ('details',array( 'prdd' => Sanpham::model()->findAll($spCriteria), 'com1'=>  Hangsx::model()->findAll($comCriteria1)));
                    
                }
             else{
            
		$this->mes = "Hello from store/details";
                $this->render('indexs', array('content'=>$this->mes));}
	}

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{
		$model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$name='=?UTF-8?B?'.base64_encode($model->name).'?=';
				$subject='=?UTF-8?B?'.base64_encode($model->subject).'?=';
				$headers="From: $name <{$model->email}>\r\n".
					"Reply-To: {$model->email}\r\n".
					"MIME-Version: 1.0\r\n".
					"Content-Type: text/plain; charset=UTF-8";

				mail(Yii::app()->params['adminEmail'],$subject,$model->body,$headers);
				Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model));
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl=array('/admin/sanpham/index'));
                            //    $this->redirect(Yii::app()->user->returnUrlarray->('/admin/sanpham/index'));
		}
		// display the login form
		$this->render('login',array('model'=>$model));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
}

protected/controllers/StoreController.php
<?php

class StoreController extends Controller
{
    public $mes;
    public function actionIndex()
	{
                $this->mes = "Hello from store";
		$this->render('index', array('content'=>$this->mes));
	}
        
        public function actionBrowse()
	{
             
            if ($_GET["id"])
            {
                $comCriteria = new CDbCriteria();
                $comCriteria->select = "`MaHangSX`, `TenHangSX`";
                $comCriteria->condition = "MaHangSX = ".$_GET["id"];
                
                $comCriteria1 = new CDbCriteria();
                $comCriteria1->select = "`MaHangSX`, `TenHangSX`";
               
                
                
                $kprdCriteria = new CDbCriteria();
                $kprdCriteria -> alias = "t1";
                $kprdCriteria->select = "DISTINCT `t1`.`TenLoaiSP`, `t1`.`MaLoaiSP`";
                $kprdCriteria->join = "INNER JOIN `sanpham` ON `sanpham`.`MaLoaiSP` = `t1`.`MaLoaiSP` ";
                $kprdCriteria->condition = "`sanpham`.`MaHangSX`= ".$_GET["id"];
                
                
                $prdCriteria = new CDbCriteria();
          
                $prdCriteria->select = "*";
                $prdCriteria->condition = "MaHangSX = ".$_GET["id"];
                
                
                $count= Sanpham::model()->count($prdCriteria);
                $pages=new CPagination($count);
                
                $pages->pageSize=5;
                $pages->applyLimit($prdCriteria);
               
    
                $this->render ('index',array( 'prd' => Sanpham::model()->findAll($prdCriteria),
                                               'kprd' => Loaisp::model()->findAll($kprdCriteria),
                                                'com'=>  Hangsx::model()->findAll($comCriteria),
                                                 'com1'=>  Hangsx::model()->findAll($comCriteria1)
                                                ,'pages' => $pages));
            } 
            else
            {
               
                
                $this->mes = "Hello from store/Browse";
		$this->render('index', array('content'=>$this->mes));
            }
	}
        
        public function actionDetails()
	{
                
                
                $comCriteria1 = new CDbCriteria();
                $comCriteria1->select = "`MaHangSX`, `TenHangSX`";
                
                
        
             if ($_GET["pid"])
                {
                    $spCriteria = new CDbCriteria();
                    $spCriteria->select = "*";
                    $spCriteria->condition = "MaSP = ".$_GET["pid"];
                    
                    
                    $this->render ('details',array( 'prdd' => Sanpham::model()->findAll($spCriteria), 'com1'=>  Hangsx::model()->findAll($comCriteria1)));
                    
                }
             else{
            
		$this->mes = "Hello from store/details";
                $this->render('indexs', array('content'=>$this->mes));}
	}
        
        public function actionStarRatingAjax() {

       $ratingAjax=isset($_POST['rate']) ? $_POST['rate'] : 0;

       echo "You are voting $ratingAjax through AJAX!";

   }


	// Uncomment the following methods and override them if needed
	/*
	public function filters()
	{
		// return the filter configuration for this controller, e.g.:
		return array(
			'inlineFilterName',
			array(
				'class'=>'path.to.FilterClass',
				'propertyName'=>'propertyValue',
			),
		);
	}

	public function actions()
	{
		// return external action classes, e.g.:
		return array(
			'action1'=>'path.to.ActionClass',
			'action2'=>array(
				'class'=>'path.to.AnotherActionClass',
				'propertyName'=>'propertyValue',
			),
		);
	}
	*/
}

protected/views/site/contact.php
<?php
/* @var $this SiteController */
/* @var $model ContactForm */
/* @var $form CActiveForm */

$this->pageTitle=Yii::app()->name . ' - Contact Us';
$this->breadcrumbs=array(
	'Contact',
);
?>

<h1>Contact Us</h1>

<?php if(Yii::app()->user->hasFlash('contact')): ?>

<div class="flash-success">
	<?php echo Yii::app()->user->getFlash('contact'); ?>
</div>

<?php else: ?>

<p>
If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
</p>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'contact-form',
	'enableClientValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name'); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'email'); ?>
		<?php echo $form->textField($model,'email'); ?>
		<?php echo $form->error($model,'email'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'subject'); ?>
		<?php echo $form->textField($model,'subject',array('size'=>60,'maxlength'=>128)); ?>
		<?php echo $form->error($model,'subject'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'body'); ?>
		<?php echo $form->textArea($model,'body',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'body'); ?>
	</div>

	<?php if(CCaptcha::checkRequirements()): ?>
	<div class="row">
		<?php echo $form->labelEx($model,'verifyCode'); ?>
		<div>
		<?php $this->widget('CCaptcha'); ?>
		<?php echo $form->textField($model,'verifyCode'); ?>
		</div>
		<div class="hint">Please enter the letters as they are shown in the image above.
		<br/>Letters are not case-sensitive.</div>
		<?php echo $form->error($model,'verifyCode'); ?>
	</div>
	<?php endif; ?>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Submit'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

<?php endif; ?>

protected/views/site/error.php
<?php
/* @var $this SiteController */
/* @var $error array */

$this->pageTitle=Yii::app()->name . ' - Error';
$this->breadcrumbs=array(
	'Error',
);
?>

<h2>Error <?php echo $code; ?></h2>

<div class="error">
<?php echo CHtml::encode($message); ?>
</div>

protected/views/site/index.php
<?php
/* @var $this SiteController */

$this->pageTitle = Yii::app()->name;
?>



<div id="menul">
    <?php foreach ($Companies as $Company): ?> 
        <ul>
            <li><?php echo CHtml::link($Company->TenHangSX, array('store/browse', 'id' => $Company->MaHangSX)); ?></li>
        </ul>
    <?php endforeach; ?>
    <img src="http://localhost/Yii_WebApp_Training/images/lenovo.jpg"/>
</div>
<?php $this->widget('application.extensions.slider.slider'); ?>

<div id="slide">
    <?php
    $this->widget('ext.slider.slider', array(
        'container' => 'slideshow',
        'width' => 725,
        'height' => 320,
        'timeout' => 4000,
        'infos' => false,
        'imagesPath' => 'images',
        'constrainImage' => true,
        'images' => array('01.jpg', '02.jpg', '03.jpg', '04.jpg', '05.jpg', '06.jpg', '07.jpg'),
        //'alts'=>array('First description','Second description','Third description','Four description'),
        'defaultUrl' => Yii::app()->request->hostInfo
            )
    );
    ?>
</div>

<img src="http://localhost/Yii_WebApp_Training/images/bar1.png" width="710" />
     <div class="newprd" style="float: right; width: 710px">
<?php foreach ($newPrd as $Sanpham): ?>
    <div id="data_<?php echo $Sanpham->MaSP ?>" class="hidden-tip" style="display: none; width:400px;">

        <div class="protip-title" style="width:300px;"><?php echo $Sanpham ->TenSP ?></div>
        <div class="protip-content" style="width:280px;padding:0 10px 0 10px;text-align:justify;margin:12px 0;">
            <p class="protip-price"><label>Giá: </label><span> <?php $Sanpham ->GiaSP ?> triệu VNĐ</span></p>
            <p class="protip-warranty">
                <label>Bảo hành: </label>12 tháng                </p>
            <p class="protip-quantity">
                <label>Kho hàng: </label><span>Còn hàng</span>
            </p>
            <p class="protip-promotion">
                <label>Khuyến mãi:</label><span>Dán màn hình, giảm 10% giá phụ kiện mua kèm</span>
            </p>
            <p class="protip-summary">
                <label>Thông số kỹ thuật:</label><?php $Sanpham ->MoTaSP ?>                    </p>
        </div>
    </div>
    <div id="<?php echo $Sanpham->MaSP ?>" class="tooltip productIndexOffer " style='position:relative;'>
        <div class="proImg">
            <img src="http://localhost/Yii_WebApp_Training/images/<?php echo $Sanpham->HinhAnh ?>" width="170" border=0>
        </div>
        <div class="proTitle"><?php echo CHtml::link($Sanpham->TenSP, array('store/details', 'pid' => $Sanpham->MaSP)); ?></div>
        <div class="proPrice" style="font-size:14px;">
            Giá:  <?php echo $Sanpham ->GiaSP ?> triệu VNĐ                        </div>


        <div class="ProOrder">
            <a href="#" <?php if (isset($_SESSION['Username'])) { ?>	 onClick="chon_muahang(<?php echo $Sanpham->MaSP ?>, '<?php echo $Sanpham ->TenSP ?>', <?php echo  $Sanpham ->GiaSP ?>, 'them')" <?php } else  ?> onclick="thongbao()"><img src="http://localhost/Yii_WebApp_Training/images/cartBG1.png"  /></a>
        </div>
        <div class="pro-check-order">
            <script>checkItemInCart(<?php echo $Sanpham->MaSP ?>)</script>
            <p id=<?php echo $Sanpham->MaSP ?> ></p>
        </div>
    </div> <?php endforeach; ?>
                           
</div> 

protected/views/site/login.php
<?php
/* @var $this SiteController */
/* @var $model LoginForm */
/* @var $form CActiveForm  */

$this->pageTitle=Yii::app()->name . ' - Login';
$this->breadcrumbs=array(
	'Login',
);
?>

<h1>Login</h1>

<p>Please fill out the following form with your login credentials:</p>

<div class="form">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'login-form',
	'enableClientValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<div class="row">
		<?php echo $form->labelEx($model,'username'); ?>
		<?php echo $form->textField($model,'username'); ?>
		<?php echo $form->error($model,'username'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'password'); ?>
		<?php echo $form->passwordField($model,'password'); ?>
		<?php echo $form->error($model,'password'); ?>
		<p class="hint">
			Hint: You may login with <kbd>demo</kbd>/<kbd>demo</kbd> or <kbd>admin</kbd>/<kbd>admin</kbd>.
		</p>
	</div>

	<div class="row rememberMe">
		<?php echo $form->checkBox($model,'rememberMe'); ?>
		<?php echo $form->label($model,'rememberMe'); ?>
		<?php echo $form->error($model,'rememberMe'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Login'); ?>
	</div>

<?php $this->endWidget(); ?>
</div><!-- form -->